
auth.token=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

defaults.org=spotbuddy-rv
defaults.project=react-native

defaults.url=https://sentry.io/
